// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtficFfmQyePRXfbda6OhSautmxwKKRac',
    appId: '1:505793906042:web:687606838c9ca0650a02c3',
    messagingSenderId: '505793906042',
    projectId: 'future-capital-91977',
    authDomain: 'future-capital-91977.firebaseapp.com',
    storageBucket: 'future-capital-91977.firebasestorage.app',
    measurementId: 'G-0LE2TV0PYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-O__s6A6QTCi8qEBQWgar5RSmuOCey4',
    appId: '1:505793906042:android:6a1d9bb3ef0d6e6b0a02c3',
    messagingSenderId: '505793906042',
    projectId: 'future-capital-91977',
    storageBucket: 'future-capital-91977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavlhAh3RMEioGwFuAyJr-ZWyTYzhG5d4',
    appId: '1:505793906042:ios:deaf2130368a2bdd0a02c3',
    messagingSenderId: '505793906042',
    projectId: 'future-capital-91977',
    storageBucket: 'future-capital-91977.firebasestorage.app',
    iosBundleId: 'com.cibilfixer.partner.cibilfixerPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBavlhAh3RMEioGwFuAyJr-ZWyTYzhG5d4',
    appId: '1:505793906042:ios:deaf2130368a2bdd0a02c3',
    messagingSenderId: '505793906042',
    projectId: 'future-capital-91977',
    storageBucket: 'future-capital-91977.firebasestorage.app',
    iosBundleId: 'com.cibilfixer.partner.cibilfixerPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtficFfmQyePRXfbda6OhSautmxwKKRac',
    appId: '1:505793906042:web:4cbc9631baa6fa180a02c3',
    messagingSenderId: '505793906042',
    projectId: 'future-capital-91977',
    authDomain: 'future-capital-91977.firebaseapp.com',
    storageBucket: 'future-capital-91977.firebasestorage.app',
    measurementId: 'G-DTRWSZPPRE',
  );

}